//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartB.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredential
    {
        public int UserID { get; set; }
        public string uname { get; set; }
        public string pword { get; set; }
        public int utype { get; set; }
        public string name { get; set; }
        public string email { get; set; }
    }
}
