//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CineplexMovie
    {
        public int CineplexMovieID { get; set; }
        public int CineplexID { get; set; }
        public int MovieID { get; set; }
    
        public virtual Cineplex Cineplex { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
